### ISSUE TITLE
大佬能否出个详细教程教教怎么部署和调用呀感激不尽！！😘

### ISSUE THREAD

**Issue by maotuworkroom** [mumu-lhl/duckduckgo-ai-chat-service#2]

**Comment by mumu-lhl** [comment]
Render 部署看[这个](https://github.com/mumu-lhl/duckduckgo-ai-chat-service/blob/main/README_CN.md#render)，Deno Deploy 部署看[这个](https://github.com/mumu-lhl/duckduckgo-ai-chat-service/blob/main/README_CN.md#web)，按照流程来，很简单的，如果看不懂点哪个，可以用翻译插件。

**Comment by wanghaisheng** [comment]
@mumu-lhl 大神 我部署了一个 但为啥钓不起来  
[heisenberg-duckduckgo-87.deno.dev](https://heisenberg-duckduckgo-87.deno.dev/)

**Comment by wanghaisheng** [comment]
![image](https://github.com/user-attachments/assets/8f80bdd8-a541-4d87-a141-00f6c922d172)

**Comment by mumu-lhl** [comment]
@wanghaisheng 实际上应该是没问题的。另外测试工具能发一下吗？

**Comment by wanghaisheng** [comment]
@mumu-lhl 
https://openai-endpoint-test.borninsea.com/

https://github.com/RunningFelix/openai-api-tester

**Comment by mumu-lhl** [comment]
@wanghaisheng 用 curl 测试了一下是没问题的，应该是测试工具有点问题
